plugins {
    id 'com.android.application'
}

android {
    compileSdk 33
    namespace 'com.calculatorpro.app'

    defaultConfig {
        applicationId "com.zcalculator.app"
        minSdk 21
        targetSdk 33
        versionCode 1
        versionName "1.0"
    }

    signingConfigs {
        release {
            storeFile file('zcalculator.keystore')
            storePassword 'zcalculator123'
            keyAlias 'zcalculator'
            keyPassword 'zcalculator123'
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.release
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
}
