name: Android Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 35
        build-tools-version: '35.0.0'
        
    - name: Build Release AAB
      run: |
        ./gradlew clean bundleRelease --no-daemon --stacktrace
        
    - name: Build Debug AAB
      run: |
        ./gradlew clean bundleDebug --no-daemon
        
    - name: Upload All Bundles
      uses: actions/upload-artifact@v4
      with:
        name: app-bundles
        path: app/build/outputs/bundle/
